import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import ResponsiveNav from '@/components/Home/Navbar/ResponsiveNav';
import Footer from '@/components/Home/Footer/Footer';

const roboto = Roboto({
	weight: ['100', '300', '400', '500', '700', '900'],
	subsets: ['latin'],
	variable: '--font-roboto',
});

export const metadata: Metadata = {
	title: 'Real Astate Agensy | Next.js',
	description: 'Generated by create Real Astate Agensy Website',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${roboto.variable} antialiased`}>
				<ResponsiveNav />
				{children}
				<Footer />
			</body>
		</html>
	);
}
